# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9570091b50ac8912416deb704acde043e726f8ff76e5dccf42344834669cb8f2f5b52c3fe1d4059fa6c6b4cc35ca38cfe674b9a438a0274d5e3aeaa4377eec

test:
  secret_key_base: a6053b4253d650839c56a1f799ace8e8fd2dd45686195a4f8a181e9a8be716d07529244d7014c34877ec280cfe33a33261552c395e5cc30d94dacce5ec532a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
